status-response: "ok"
adapters:
  appnexus:
    enabled: true
  ix:
    enabled: true
  openx:
    enabled: true
  pubmatic:
    enabled: true
  rubicon:
    enabled: true
metrics:
  prefix: prebid
cache:
  scheme: http
  host: localhost
  path: /cache
  query: uuid=
settings:
  enforce-valid-account: false
  generate-storedrequest-bidrequest-id: true
  filesystem:
    settings-filename: sample/configs/sample-app-settings.yaml
    stored-requests-dir: sample
    stored-imps-dir: sample
    stored-responses-dir: sample
    categories-dir:
  default-account-config: >
    {
      "auction": {
        "price-floors": {
          "enabled": true,
          "fetch": {
            "enabled": false,
            "timeout-ms": 5000,
            "max-rules": 0,
            "max-file-size-kb": 200,
            "max-age-sec": 86400,
            "period-sec": 3600
          },
          "enforce-floors-rate": 100,
          "adjust-for-bid-adjustment": true,
          "enforce-deal-floors": true,
          "use-dynamic-data": true
        }
      },
      "hooks": {
          "modules": {
              "greenbids": {
                  "enabled": true,
                  "pbuid": "PBUID_FROM_GREENBIDS",
                  "targetTpr": 0.95,
                  "explorationRate": 0.001
              }
          }
      },
      "analytics": {
          "modules": {
              "greenbids": {
                  "enabled": true,
                  "pbuid": "PBUID_FROM_GREENBIDS",
                  "greenbidsSampling": 0.001
                }
            }
        }
    }
gdpr:
  default-value: 1
  vendorlist:
    v2:
      cache-dir: /var/tmp/vendor2
    v3:
      cache-dir: /var/tmp/vendor3
admin-endpoints:
  logging-changelevel:
    enabled: true
    path: /logging/changelevel
    on-application-port: true
    protected: false
hooks:
  greenbids-real-time-data:
    enabled: true
  confiant-ad-quality:
    enabled: true
  host-execution-plan: >
    {
      "endpoints": {
        "/openrtb2/auction": {
          "stages": {
            "processed-auction-request": {
              "groups": [
                {
                  "timeout": 100,
                  "hook-sequence": [
                    {
                      "module-code": "greenbids-real-time-data",
                      "hook-impl-code": "greenbids-real-time-data-processed-auction-request"
                    }
                  ]
                }
              ]
            },
            "all-processed-bid-responses": {
              "groups": [
                {
                  "timeout": 100,
                  "hook-sequence": [
                    {
                      "module-code": "confiant-ad-quality",
                      "hook-impl-code": "confiant-ad-quality-bid-responses-scan-hook"
                    }
                  ]
                }
              ]
            }
          }
        }
      }
    }
  modules:
    confiant-ad-quality:
      api-key: "hgr876cerg7655"
      redis-config:
        write-node:
          host: "127.0.0.1"
          port: 8467
          password: "password-w"
        read-node:
          host: "127.0.0.1"
          port: 8468
          password: "password-r"
      redis-retry-config:
        short-interval-attempts: 60
        short-interval: 1000
        long-interval-attempts: 336
        long-interval: 1800000
      scan-state-check-interval: 2900
      bidders-to-exclude-from-scan:
    greenbids-real-time-data:
      google-cloud-greenbids-project: "greenbids-357713"
      gcs-bucket-name: "greenbids-europe-west1-prebid-server-staging"
      cache-expiration-minutes: 15
      geo-lite-country-path: "TOREPLACEWITHURL"
      onnx-model-cache-key-prefix: "onnxModelRunner_"
      thresholds-cache-key-prefix: "throttlingThresholds_"
      timeout-ms: 10000
